<?php

return[
    'Accounting'=>'Accounting',
    'Budget'=>'Budget',
    'Cashier'=>'Cashier',
    'Community Empowerment through Science and Technology'=>'Community Empowerment through Science and Technology',
    'Cordillera Industry, Energy and Emerging Technology Research and Development Consortium'=>'Cordillera Industry, Energy and Emerging Technology Research and Development Consortium',
    'Cordillera Regional Health Research and Development'=>'Cordillera Regional Health Research and Development',
    'Disaster Risk Reduction Management'=>'Disaster Risk Reduction Management',
    'Fairness Opinion Board'=>'Fairness Opinion Board',
    'FAS - Office of the ARD'=>'FAS - Office of the ARD',
    'Food Innovation Center'=>'Food Innovation Center',
    'Gender & Development'=>'Gender & Development',
    'General Services'=>'General Services',
    'Halal'=>'Halal',
    'Human Resource Management'=>'Human Resource Management',
    'Local Grant-in-Aid'=>'Local Grant-in-Aid',
    'Management Information System'=>'Management Information System',
    'Office of the Regional Director'=>'Office of the Regional Director',
    'Packaging and Labelling'=>'Packaging and Labelling',
    'Planning'=>'Planning',
    'Property and Supply'=>'Property and Supply',
    'PSTC - Abra'=>'PSTC - Abra',
    'PSTC - Apayao'=>'PSTC - Apayao',
    'PSTC - Benguet'=>'PSTC - Benguet',
    'PSTC - Ifugao'=>'PSTC - Ifugao',
    'PSTC - Kalinga'=>'PSTC - Kalinga',
    'PSTC - Mountain Province'=>'PSTC - Mountain Province',
    'PSTC - Records'=>'PSTC - Records',
    'PSTC - Regional Metrology Laboratory'=>'PSTC - Regional Metrology Laboratory',
    'PSTC - Regional Research Development and Innovation Commitee'=>'PSTC - Regional Research Development and Innovation Commitee',
    'PSTC - Regional Standards and Testing Laboratory'=>'PSTC - Regional Standards and Testing Laboratory',
    'PSTC - RxBox'=>'PSTC - RxBox',
    'PSTC - Scholarship'=>'PSTC - Scholarship',
    'PSTC - Science and Technology Promotion'=>'PSTC - Science and Technology Promotion',
    'PSTC - Sericulture'=>'PSTC - Sericulture',
    'PSTC - SETUP'=>'PSTC - SETUP',
    'PSTC - TSD - Office of the ARD'=>'PSTC - TSD - Office of the ARD',

];